pipeline {
 agent any
 stages{
    stage('Verify tooling') {
        steps {
            sh '''
            docker images
            docker info
            docker version
            docker compose version 
            curl --version
            jq --version
            '''
        }
      }
    }
}