pipeline {
 agent any
 stages{
    stage('Verify tooling') {
        steps {
            sh '''
            docker images
            docker info
            docker version
            
            docker-compose up -d //Run on the Detach mode
            '''
        }
      }
    }
}