pipeline {
 agent any
 stages{
    stage('Build and Deploy Container') {
        steps {
            sh '''
            docker images
            docker info
            docker version
            docker-compose build
            docker-compose up -d 
            '''
        }
      }
    }
}